/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void slider1_change1(GSlider source, GEvent event) { //_CODE_:slider1:993061:
  logInterval = slider1.getValueI();
} //_CODE_:slider1:993061:

public void slider2_change1(GSlider source, GEvent event) { //_CODE_:slider2:408580:
  launchDay = slider2.getValueI();
} //_CODE_:slider2:408580:

public void slider3_change1(GSlider source, GEvent event) { //_CODE_:slider3:870109:
  launchHour = slider3.getValueI();
} //_CODE_:slider3:870109:

public void slider4_change1(GSlider source, GEvent event) { //_CODE_:slider4:556373:
  launchMin = slider4.getValueI();
} //_CODE_:slider4:556373:

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:957917:
  if(!launchFlag && !errorFlag) launch();
} //_CODE_:button1:957917:

public void dropList1_click1(GDropList source, GEvent event) { //_CODE_:dropList1:824312:
  launchPortIndex = dropList1.getSelectedIndex();
} //_CODE_:dropList1:824312:

public void dropList2_click1(GDropList source, GEvent event) { //_CODE_:dropList1:824312:
  secMinHourIndex = dropList2.getSelectedIndex();
  println(secMinHourIndex);
  switch(secMinHourIndex) {
    case 0:
      slider1.setLimits(logInterval, 10, 59);
      logInterval = 10;
      break;
    case 1:
      slider1.setLimits(logInterval, 1, 59);
      //logInterval = 1;
      break;
    case 2:
      slider1.setLimits(logInterval, 1, 23);
      break;
  }  
} //_CODE_:dropList2:824212:

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:textfield1:264079:
  println("textfield1 - GTextField event occured " + System.currentTimeMillis()%10000000 );
  logFileName = textfield1.getText();
} //_CODE_:textfield1:264079:


// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  if(frame != null)
    frame.setTitle("OSBSS LOGGER LAUNCHER");
  slider1 = new GSlider(this, 20, 20, 240, 30, 10.0);
  slider1.setLimits(logInterval, 10, 59);
  slider1.setNumberFormat(G4P.INTEGER, 0);
  slider1.setOpaque(false);
  slider1.addEventHandler(this, "slider1_change1");
  slider2 = new GSlider(this, 20, 60, 240, 30, 10.0);
  slider2.setLimits(launchDay, 1, 31);
  slider2.setNumberFormat(G4P.INTEGER, 0);
  slider2.setOpaque(false);
  slider2.addEventHandler(this, "slider2_change1");
  slider3 = new GSlider(this, 20, 100, 240, 30, 10.0);
  slider3.setLimits(launchHour, 0, 23);
  slider3.setNumberFormat(G4P.INTEGER, 0);
  slider3.setOpaque(false);
  slider3.addEventHandler(this, "slider3_change1");
  slider4 = new GSlider(this, 20, 140, 240, 30, 10.0);
  slider4.setLimits(launchMin, 1, 59);
  slider4.setNumberFormat(G4P.INTEGER, 0);
  slider4.setOpaque(false);
  slider4.addEventHandler(this, "slider4_change1");
  button1 = new GButton(this, 20, 320, 440, 30);
  button1.setText("Launch");
  button1.setTextBold();
  button1.addEventHandler(this, "button1_click1");
  dropList1 = new GDropList(this, 20, 230, 280, 90, 3);
  dropList1.setItems(Serial.list(), 1);
  dropList1.addEventHandler(this, "dropList1_click1");
  dropList2 = new GDropList(this, 418, 23, 40, 90, 3);
  dropList2.setItems(secMinHour, 0);
  dropList2.addEventHandler(this, "dropList2_click1");
  textfield1 = new GTextField(this, 20, 185, 80, 20, G4P.SCROLLBARS_NONE);
  textfield1.setText(logFileName);
  textfield1.setOpaque(false);
  textfield1.addEventHandler(this, "textfield1_change1");
}

// Variable declarations 
// autogenerated do not edit
GSlider slider1; 
GSlider slider2; 
GSlider slider3; 
GSlider slider4; 
GButton button1; 
GDropList dropList1; 
GDropList dropList2; 
GTextField textfield1; 

